import re
import ollama


LLM_MODEL = "llama3.2:3b"


def _build_prompt(query, context):
    return f"""
You are a helpful AI Assistant for company policies.

Answer the employee's question using ONLY the provided POLICY CONTEXT.

Instructions:
1. Provide a clear, natural, and concise answer with just the relevant facts.
2. Start directly with the answer. Do NOT use conversational preambles or intros like "Here is the answer...", "Here's a clear and helpful answer...", "Based on the policy context...", "According to the context provided...", or "To answer your question...".
3. Do NOT include document metadata headers like Policy IDs, version numbers, or effective dates unless specifically asked.
4. Do NOT add trailing filler like "Would you like to know more?", "Feel free to ask!", or closing signatures.
5. Do NOT answer math, trivia, coding, or off-topic questions.
6. If the answer cannot be found in the policy context, say:
   "I couldn't find that information in the company policies."

POLICY CONTEXT:
{context}

EMPLOYEE QUESTION:
{query}

ANSWER:
"""


def _clean_response(content: str) -> str:
    """Strips any thinking/reasoning blocks if generated by reasoning models."""
    if not content:
        return ""
    if "</think>" in content:
        content = content.split("</think>", 1)[1]
    elif "<think>" in content:
        content = re.sub(r"<think>.*?</think>", "", content, flags=re.DOTALL)
    return content.strip()


def generate_answer(query, context):

    prompt = _build_prompt(query, context)

    response = ollama.chat(
        model=LLM_MODEL,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        options={
            "temperature": 0.2
        },
        keep_alive="1h"
    )

    raw_content = response.get("message", {}).get("content", "")
    return _clean_response(raw_content)


def generate_answer_stream(query, context):

    prompt = _build_prompt(query, context)

    stream = ollama.chat(
        model=LLM_MODEL,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        options={
            "temperature": 0.2
        },
        stream=True,
        keep_alive="1h"
    )

    buffer = ""
    has_seen_think_end = False

    for chunk in stream:
        content = chunk.get("message", {}).get("content", "")
        if not content:
            continue

        if "<think>" in content or "</think>" in content:
            buffer += content
            if "</think>" in buffer:
                has_seen_think_end = True
                after_think = buffer.split("</think>", 1)[1]
                buffer = ""
                clean_start = after_think.lstrip("\r\n ")
                if clean_start:
                    yield clean_start
            continue

        yield content

    if buffer and not has_seen_think_end:
        yield _clean_response(buffer)